sudo: required
services:
        - docker

before_install:
        - docker build -t alexalex99922/docker-react -f Dockerfile.dev .

script:
        - docker run alexalex99922/docker-react npm run test -- --coverage
